/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef MIBIEEE80222_H
#define MIBIEEE80222_H

/* function declarations */
void init_mibIEEE80222(void);
FindVarMethod var_mibIEEE80222;
    WriteMethod write_wranIfSmSsaChAvailabilityCheckTime;
    WriteMethod write_wranIfSmSsaNonOccupancyPeriod;
    WriteMethod write_wranIfSmSsaChannelOpeningTxTime;
    WriteMethod write_wranIfSmManagedChannel;
    WriteMethod write_wranIfSsaSensingChannel;
    WriteMethod write_DecisionGamaWeight;
    WriteMethod write_DecisionRssiMinValue;
    WriteMethod write_DecisionRssiMaxValue;
    WriteMethod write_wranIfGenericObj1;
    WriteMethod write_wranIfGenericObj2;
    WriteMethod write_wranIfGenericObj3;
    WriteMethod write_wranIfGenericObj4;
    WriteMethod write_wranIfGenericObj5;
    WriteMethod write_wranIfGenericObj6;
    WriteMethod write_wranIfGenericObj7;
    WriteMethod write_wranIfGenericObj8;

#endif /* MIBIEEE80222_H */
